### DISCUSSION TITLE
How can I change the default icon size in React?

### DISCUSSION THREAD

**Discussion by wenchonglee** [tabler/tabler-icons#577] [Q&A]
Hey,

Is there a good way to change the default size of icons, say from 24px to 20px?
Initially I opted to use something like below, but it will override every instance; causing changes to the `size` prop to not work.

```css
svg.tabler-icon {
  width: 20px;
  height: 20px;
}
```

```js
<IconApple size={32} /> // will be 20px even with the size prop, because the css overrides it
```
