### ISSUE TITLE
The filled and outlined versions cannot co-exist using the webfont version

### ISSUE THREAD

**Issue by sethyuan** [tabler/tabler-icons#1042]
The CSS is defined like this, which obvious won't have the 2 versions coexist:

```css
@font-face {
  font-family: "tabler-icons-filled";
  font-style: normal;
  font-weight: 400;
  src: url("./fonts/tabler-icons-filled.woff2?v3.0.0") format("woff2"), url("./fonts/tabler-icons-filled.woff?") format("woff"), url("./fonts/tabler-icons-filled.ttf?v3.0.0") format("truetype");
}
.ti {
  font-family: "tabler-icons-filled" !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  /* Better Font Rendering */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.ti-accessible:before {
  content: "\f6ea";
}
```
