### ISSUE TITLE
Allow css/webfont to work out of the box in more settings

### ISSUE THREAD

**Issue by jourdain** [tabler/tabler-icons#1094]
Currently, the CSS set the __font-family__ on the class and omits the __:before__ modifier, which allows other CSS to override it.

Adding the following will fix such issue. 

```css
.ti:before {
  font-family:tabler-icons !important;
}
```

For context, I could skip my [add-on CSS](https://github.com/Kitware/trame/blob/master/examples/validation/discussion/495.py#L23) if it was part of [your CSS](https://github.com/Kitware/trame/blob/master/examples/validation/discussion/495.py#L15).

Looking at the code, it seems that it could be done in `tabler-icons/packages/icons-webfront/.build/iconfront.scss`

```scss
.#{$ti-prefix}, .#{$ti-prefix}:before {
  font-family: $ti-font-family !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

Thanks for considering my suggestion.
