### ISSUE TITLE
Strange bold rendering on Chrome

### ISSUE THREAD

**Issue by n9** [tabler/tabler-icons#626]
Certain parts of some characters gets "strange outline" when rendered on Chrome with bold font-weight.

![image](https://user-images.githubusercontent.com/1651867/231223682-35488eb2-5f91-443d-9c5d-6a0d84763441.png)

Live example here: https://jsbin.com/tuwofazaxa/1/edit?html,css,output

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Icon</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.15.0/tabler-icons.min.css">
</head>
<body>
  <div class="w100">
    <span class="menu"></span>
    <span class="terminal"></span>
    <span class="airballon"></span>
    <span class="ab"></span>
  </div>
  <div class="w599">
    <span class="menu"></span>
    <span class="terminal"></span>
    <span class="airballon"></span>
    <span class="ab"></span>
  </div>
  <div class="w600">
    <span class="menu"></span>
    <span class="terminal"></span>
    <span class="airballon"></span>
    <span class="ab"></span>
  </div>
  <div class="w1000">
    <span class="menu"></span>
    <span class="terminal"></span>
    <span class="airballon"></span>
    <span class="ab"></span>
  </div>
</body>
</html>
```

```css
div {
    font-size: 600%;
    font-family: 'tabler-icons';
}

.w100 {
    font-weight: 100;
}

.w599 {
    font-weight: 599;
}

.w600 {
    font-weight: 600;
}

.w1000 {
    font-weight: 1000;
}

.menu::before {
    content: '\eaeb';
}

.terminal::before {
    content: '\ec8f';
}

.airballon::before {
    content: '\f4a6';
}

.ab::before {
    content: '\eca0';
}
```
