### ISSUE TITLE
Tailwind classes as SVG data URLs?

### ISSUE THREAD

**Issue by whaaaley** [tabler/tabler-icons#653]
In some of my projects I'm using Sass's custom function API to use Tabler icons as SVG data URLs. An example of what that looks like here: <https://github.com/whaaaley/toolchain-vue/blob/main/toolchain/sass-functions/tabler.js>

And you'd use it like this:

```scss
// input
.tabler-alien {
  background: tabler("alien", 2, #fff) center left 12px / 24px no-repeat;
}

// output
.tabler-alien {
  background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' stroke-width='2' stroke='white' fill='none' stroke-linecap='round' stroke-linejoin='round'%3e%3cpath d='M11 17a2.5 2.5 0 0 0 2 0'/%3e%3cpath d='M12 3c-4.664 0 -7.396 2.331 -7.862 5.595a11.816 11.816 0 0 0 2 8.592a10.777 10.777 0 0 0 3.199 3.064c1.666 1 3.664 1 5.33 0a10.777 10.777 0 0 0 3.199 -3.064a11.89 11.89 0 0 0 2 -8.592c-.466 -3.265 -3.198 -5.595 -7.862 -5.595z'/%3e%3cpath d='M8 11l2 2'/%3e%3cpath d='M16 11l-2 2'/%3e%3c/svg%3e") center left 12px/24px no-repeat;
}
```

But, for the last year or so I've swapped to Tailwind for many of my projects. I'd still like to use utility classes for icons rather than icon components, personally. Would Tailwind utility classes be something this project is open to adding? Just trying to plan ahead before I go off and do something crazy like start my own project. 😅 

What I'm imagining is something akin to this syntax:

```html
<div class='pl-8 bg-tabler-alien'>
  There's an alien near me!
</div>
```
![image](https://user-images.githubusercontent.com/7419947/236639608-8fd3f2f3-4022-4a6b-82d0-6128a8632cc7.png)

Positioning could be changed by adding regular bg utilities

```html
<div class='pl-8 bg-tabler-alien bg-right-center'>
  There's an alien near me!
</div>
```
![image](https://user-images.githubusercontent.com/7419947/236639581-faef3398-c25f-46ee-8dfd-eb95a84d086a.png)

I realize something like this could very well be out of scope for this project. Would still be nice though!
